apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample19
  labels:
    app: sample19
spec:
  replicas: 1
  template:
    metadata:
      name: sample19
      labels:
        app: sample19
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sample19
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        resources:
          limits:
            cpu: 1
            memory: 800M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: sample19
---
apiVersion: v1
kind: Service
metadata:
  name: sample19
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: sample19
  externalTrafficPolicy: Local