// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.0
// source: hcn.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HCNType int32

const (
	HCNType_loadbalancers HCNType = 0
	HCNType_endpoints     HCNType = 1
	HCNType_networks      HCNType = 2
)

// Enum value maps for HCNType.
var (
	HCNType_name = map[int32]string{
		0: "loadbalancers",
		1: "endpoints",
		2: "networks",
	}
	HCNType_value = map[string]int32{
		"loadbalancers": 0,
		"endpoints":     1,
		"networks":      2,
	}
)

func (x HCNType) Enum() *HCNType {
	p := new(HCNType)
	*p = x
	return p
}

func (x HCNType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HCNType) Descriptor() protoreflect.EnumDescriptor {
	return file_hcn_proto_enumTypes[0].Descriptor()
}

func (HCNType) Type() protoreflect.EnumType {
	return &file_hcn_proto_enumTypes[0]
}

func (x HCNType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HCNType.Descriptor instead.
func (HCNType) EnumDescriptor() ([]byte, []int) {
	return file_hcn_proto_rawDescGZIP(), []int{0}
}

// requests
type HCNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hcntype HCNType `protobuf:"varint,1,opt,name=hcntype,proto3,enum=winspect.hcn.HCNType" json:"hcntype,omitempty"`
}

func (x *HCNRequest) Reset() {
	*x = HCNRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hcn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HCNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HCNRequest) ProtoMessage() {}

func (x *HCNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hcn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HCNRequest.ProtoReflect.Descriptor instead.
func (*HCNRequest) Descriptor() ([]byte, []int) {
	return file_hcn_proto_rawDescGZIP(), []int{0}
}

func (x *HCNRequest) GetHcntype() HCNType {
	if x != nil {
		return x.Hcntype
	}
	return HCNType_loadbalancers
}

// responses
type HCNResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HcnResult []byte `protobuf:"bytes,1,opt,name=hcn_result,json=hcnResult,proto3" json:"hcn_result,omitempty"`
}

func (x *HCNResponse) Reset() {
	*x = HCNResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hcn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HCNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HCNResponse) ProtoMessage() {}

func (x *HCNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hcn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HCNResponse.ProtoReflect.Descriptor instead.
func (*HCNResponse) Descriptor() ([]byte, []int) {
	return file_hcn_proto_rawDescGZIP(), []int{1}
}

func (x *HCNResponse) GetHcnResult() []byte {
	if x != nil {
		return x.HcnResult
	}
	return nil
}

var File_hcn_proto protoreflect.FileDescriptor

var file_hcn_proto_rawDesc = []byte{
	0x0a, 0x09, 0x68, 0x63, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77, 0x69, 0x6e,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x68, 0x63, 0x6e, 0x22, 0x3d, 0x0a, 0x0a, 0x48, 0x43, 0x4e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x68, 0x63, 0x6e, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x77, 0x69, 0x6e, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x2e, 0x68, 0x63, 0x6e, 0x2e, 0x48, 0x43, 0x4e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x68, 0x63, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2c, 0x0a, 0x0b, 0x48, 0x43, 0x4e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x63, 0x6e, 0x5f, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x68, 0x63, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x39, 0x0a, 0x07, 0x48, 0x43, 0x4e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x11, 0x0a, 0x0d, 0x6c, 0x6f, 0x61, 0x64, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x72, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x10,
	0x02, 0x32, 0x51, 0x0a, 0x0a, 0x48, 0x43, 0x4e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x43, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x48, 0x43, 0x4e, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x18, 0x2e,
	0x77, 0x69, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2e, 0x68, 0x63, 0x6e, 0x2e, 0x48, 0x43, 0x4e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x77, 0x69, 0x6e, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x2e, 0x68, 0x63, 0x6e, 0x2e, 0x48, 0x43, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x77, 0x69, 0x6e,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_hcn_proto_rawDescOnce sync.Once
	file_hcn_proto_rawDescData = file_hcn_proto_rawDesc
)

func file_hcn_proto_rawDescGZIP() []byte {
	file_hcn_proto_rawDescOnce.Do(func() {
		file_hcn_proto_rawDescData = protoimpl.X.CompressGZIP(file_hcn_proto_rawDescData)
	})
	return file_hcn_proto_rawDescData
}

var file_hcn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hcn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hcn_proto_goTypes = []interface{}{
	(HCNType)(0),        // 0: winspect.hcn.HCNType
	(*HCNRequest)(nil),  // 1: winspect.hcn.HCNRequest
	(*HCNResponse)(nil), // 2: winspect.hcn.HCNResponse
}
var file_hcn_proto_depIdxs = []int32{
	0, // 0: winspect.hcn.HCNRequest.hcntype:type_name -> winspect.hcn.HCNType
	1, // 1: winspect.hcn.HCNService.GetHCNLogs:input_type -> winspect.hcn.HCNRequest
	2, // 2: winspect.hcn.HCNService.GetHCNLogs:output_type -> winspect.hcn.HCNResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hcn_proto_init() }
func file_hcn_proto_init() {
	if File_hcn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hcn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HCNRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hcn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HCNResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hcn_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hcn_proto_goTypes,
		DependencyIndexes: file_hcn_proto_depIdxs,
		EnumInfos:         file_hcn_proto_enumTypes,
		MessageInfos:      file_hcn_proto_msgTypes,
	}.Build()
	File_hcn_proto = out.File
	file_hcn_proto_rawDesc = nil
	file_hcn_proto_goTypes = nil
	file_hcn_proto_depIdxs = nil
}
