FROM mcr.microsoft.com/oss/kubernetes/windows-host-process-containers-base-image:v0.1.0

ENV PATH="C:\Windows\system32;C:\Windows;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;"
WORKDIR /debug

ADD ./wcnspectserv.exe /debug
