apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: wcnspect-server
  name: wcnspect-server
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: wcnspect-server
  template:
    metadata:
      labels:
        app: wcnspect-server
      name: wcnspect-server
      namespace: kube-system
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
        runAsNonRoot: false
      hostNetwork: true
      containers:
      - name: windowswcnspectserver
        image: ghcr.io/microsoft/wcnspect:latest
        command:
        - /hpc/wcnspectserv.exe # can add `-p {num}` here to change server's port
        securityContext:
          privileged: true
      nodeSelector:
        kubernetes.io/os: windows
 